on:
  pull_request:
    paths:
      - .github/workflows/build.yml
      - 'src/**'
      - 'tests/**'
  push:
    paths:
      - .github/workflows/build.yml
      - 'src/**'
      - 'tests/**'
  workflow_dispatch:

env:
  DOTNET_VERSION: 10.0

jobs:
  build:
    runs-on: ${{ matrix.runs-on }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        runtime:
          - linux-arm64
          - linux-x64
          - osx-arm64
          - osx-x64
          - win-arm64
          - win-x64
        include:
          - runtime: linux-arm64
            runs-on: ubuntu-24.04-arm
          - runtime: linux-x64
            runs-on: ubuntu-latest
          - runtime: osx-arm64
            runs-on: macos-15-intel
          - runtime: osx-x64
            runs-on: macos-latest
          - runtime: win-arm64
            runs-on: windows-11-arm
          - runtime: win-x64
            runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          filter: tree:0

      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - id: get-version
        shell: bash
        run: |
          echo "VERSION=$(git describe --tags | sed 's/^v//')" >> "$GITHUB_OUTPUT"

      - shell: bash
        run: |
          dotnet publish src/Lip.Cli \
            -o bin \
            -p:DebugType=embedded \
            -p:Version=${{ steps.get-version.outputs.VERSION }}

      - shell: bash
        run: |
          dotnet publish src/Lip.Daemon \
            -o bin \
            -p:DebugType=embedded \
            -p:Version=${{ steps.get-version.outputs.VERSION }}

      - uses: actions/upload-artifact@v7
        with:
          name: lip-${{ steps.get-version.outputs.VERSION }}-${{ matrix.runtime }}
          path: bin/

  build-windows-installer:
    needs: build
    permissions:
      contents: read
    strategy:
      matrix:
        runtime:
          - arm64
          - x64
        include:
          - runtime: arm64
            runs-on: windows-11-arm
          - runtime: x64
            runs-on: windows-latest
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          filter: tree:0

      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - id: get-version
        shell: bash
        run: |
          echo "VERSION=$(git describe --tags | sed 's/^v//')" >> "$GITHUB_OUTPUT"

      - uses: actions/download-artifact@v8
        with:
          name: lip-${{ steps.get-version.outputs.VERSION }}-win-${{ matrix.runtime }}
          path: bin/

      - run: sed -i "s/0.0.0/${{ steps.get-version.outputs.VERSION }}/g" "src/Lip.Installer/Package.wxs"
        shell: bash

      - run: >
          dotnet build src/Lip.Installer
          -c Release
          -o bin-installer
          -p:Platform=${{ matrix.runtime }}

      - uses: actions/upload-artifact@v7
        with:
          name: lip-installer-${{ steps.get-version.outputs.VERSION }}-win-${{ matrix.runtime }}
          path: bin-installer/

  check-style:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - run: |
          dotnet format \
            --verify-no-changes

  test:
    runs-on: ${{ matrix.runs-on }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          - macos-15-intel
          - macos-latest
          - ubuntu-24.04-arm
          - ubuntu-latest
          - windows-11-arm
          - windows-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - run: |
          dotnet test
