on:
  release:
    types:
      - published

env:
  DOTNET_VERSION: 10.0

jobs:
  build:
    runs-on: ${{ matrix.runs-on }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        runtime:
          - linux-arm64
          - linux-x64
          - osx-arm64
          - osx-x64
          - win-arm64
          - win-x64
        include:
          - runtime: linux-arm64
            runs-on: ubuntu-24.04-arm
          - runtime: linux-x64
            runs-on: ubuntu-latest
          - runtime: osx-arm64
            runs-on: macos-15-intel
          - runtime: osx-x64
            runs-on: macos-latest
          - runtime: win-arm64
            runs-on: windows-11-arm
          - runtime: win-x64
            runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          filter: tree:0

      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - id: get-version
        shell: bash
        run: |
          echo "VERSION=$(git describe --tags | sed 's/^v//')" >> "$GITHUB_OUTPUT"

      - shell: bash
        run: |
          dotnet publish src/Lip.Cli \
            -o bin \
            -p:DebugType=embedded \
            -p:Version=${{ steps.get-version.outputs.VERSION }}

      - shell: bash
        run: |
          dotnet publish src/Lip.Daemon \
            -o bin \
            -p:DebugType=embedded \
            -p:Version=${{ steps.get-version.outputs.VERSION }}

      - uses: actions/upload-artifact@v7
        with:
          name: lip-${{ steps.get-version.outputs.VERSION }}-${{ matrix.runtime }}
          path: bin/

  build-windows-installer:
    needs: build
    permissions:
      contents: read
    strategy:
      matrix:
        runtime:
          - arm64
          - x64
        include:
          - runtime: arm64
            runs-on: windows-11-arm
          - runtime: x64
            runs-on: windows-latest
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          filter: tree:0

      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - id: get-version
        shell: bash
        run: |
          echo "VERSION=$(git describe --tags | sed 's/^v//')" >> "$GITHUB_OUTPUT"

      - uses: actions/download-artifact@v8
        with:
          name: lip-${{ steps.get-version.outputs.VERSION }}-win-${{ matrix.runtime }}
          path: bin/

      - name: Generate clean version 
        run: |
          version=${{ steps.get-version.outputs.VERSION }}
          sed -i "s/0.0.0/${version%%-*}/g" "src/Lip.Installer/Package.wxs"
        shell: bash

      - shell: bash
        run: |
          dotnet build src/Lip.Installer \
            -c Release \
            -o bin-installer \
            -p:Platform=${{ matrix.runtime }}

      - run: |
          mv bin-installer/en-US/Lip.Installer.msi bin-installer/en-US/lip-${{ steps.get-version.outputs.VERSION }}-win-${{ matrix.runtime }}.msi

      - uses: actions/upload-artifact@v7
        with:
          archive: false
          path: bin-installer/en-US/lip-${{ steps.get-version.outputs.VERSION }}-win-${{ matrix.runtime }}.msi

      - uses: softprops/action-gh-release@v2
        with:
          files: bin-installer/en-US/lip-${{ steps.get-version.outputs.VERSION }}-win-${{ matrix.runtime }}.msi

  update-notes:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - id: extract-release-notes
        uses: ffurrer2/extract-release-notes@v3

      - uses: softprops/action-gh-release@v2
        with:
          body: ${{ steps.extract-release-notes.outputs.release_notes }}

  upload-assets:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs:
      - build
    strategy:
      fail-fast: false
      matrix:
        runtime:
          - linux-arm64
          - linux-x64
          - osx-arm64
          - osx-x64
          - win-arm64
          - win-x64
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          filter: tree:0

      - id: get-version
        run: |
          echo "VERSION=$(git describe --tags | sed 's/^v//')" >> "$GITHUB_OUTPUT"

      - uses: actions/download-artifact@v8
        with:
          name: lip-${{ steps.get-version.outputs.VERSION }}-${{ matrix.runtime }}
          path: artifact/

      - run: |
          cp CHANGELOG.md COPYING README.md artifact/

      - working-directory: artifact
        run: |
          if [[ "${{ matrix.runtime }}" == win* ]]; then
            zip -r ../lip-${{ steps.get-version.outputs.VERSION }}-${{ matrix.runtime }}.zip *
          else
            tar -czvf ../lip-${{ steps.get-version.outputs.VERSION }}-${{ matrix.runtime }}.tar.gz *
          fi

      - uses: softprops/action-gh-release@v2
        with:
          files: |
            lip-${{ steps.get-version.outputs.VERSION }}-${{ matrix.runtime }}.*

  publish-winget:
    runs-on: windows-latest
    env:
      WINGET_CREATE_GITHUB_TOKEN: ${{ secrets.WINGET_CREATE_GITHUB_TOKEN }}
    needs:
      - upload-assets
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          filter: tree:0

      - id: get-version
        shell: bash
        run: |
          echo "VERSION=$(git describe --tags | sed 's/^v//')" >> "$GITHUB_OUTPUT"

      - run: |
          $arm64Url = "https://github.com/futrime/lip/releases/download/v${{ steps.get-version.outputs.VERSION }}/lip-${{ steps.get-version.outputs.VERSION }}-win-arm64.zip"
          $x64Url = "https://github.com/futrime/lip/releases/download/v${{ steps.get-version.outputs.VERSION }}/lip-${{ steps.get-version.outputs.VERSION }}-win-x64.zip"

          curl -JLO https://aka.ms/wingetcreate/latest
          .\wingetcreate.exe update futrime.lip `
            --submit `
            --urls "$arm64Url" "$x64Url" `
            --version "${{ steps.get-version.outputs.VERSION }}" 
